gridsat_crop_fengwu_pre: &gridsat_crop_fengwu_pre
  type: 'gridsat_crop_fengwu_pre'
  data_dir: 'cephnew:s3://tropical_cyclone_data/GRIDSAT/npy_fengwu_era5'
  save_meanstd_dir: &save_meanstd_dir 'dataset/npy_fengwu_era5_meanstd_140'
  IBTrACS_url: "dataset/ibtracs.ALL.list.v04r00.csv"
  input_length: &input_length 4
  output_length: &output_length 8
  output_step_length: &output_step_length 1
  resolution: 0.25
  radius: 5

  ERA5_image_size: &ERA5_image_size 40
  is_fengwu_pre: True

  is_use_singel_msw: &is_use_singel_msw False
  msw_mslp_choose: &msw_mslp_choose [25]
  mswname: &mswname "MSW25"

  fengwu_crop_base_dir: "cephnew:s3://tropical_cyclone_data/Fengwu_pretrain_v2_pre_crop"
  is_map_inp_intensity: False
  is_save_npy: False
  is_load_npy: True
  inp_type: &inp_type ["ERA5", "Seq"]
  set_IR_zero: False
  set_ERA5_zero: False
  set_Seq_zero: False
  train_begin_year: 2017
  train_end_year: 2017
  valid_begin_year: 2019
  valid_end_year: 2020
  test_begin_year: 2018
  test_end_year: 2018
  is_rand_rotation: False
  is_data_augmentation: False
  is_diff: &is_diff False
  is_use_lifetime_num: &is_use_lifetime_num False

  is_use_fengwu: False
  is_use_fengwu_crop: False

  is_hid_vq: &is_hid_vq False
  is_add_data: True
  add_config:
    add_data_path: "cephnew:s3://tropical_cyclone_data/npy_fengwu_era5_PI"
  is_train_fengwu_crop: False
  train_fengwu_crop_year_list: [2021]
  vnames:
    constants: []
    single_level_vnames: &single_level_vnames ['u10', 'v10', 't2m', 'msl']
    multi_level_vnames: &multi_level_vnames ['z', 'q', 'u', 'v', 't']
    hight_level_list: &hight_level_list [50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]
    #"USA_WIND", "USA_PRES"
    label_vnames: &label_vnames ["USA_WIND", "USA_PRES"]

    is_pre_latlon: False
   
    train_label_Basin: ["EP", "NA", "NI", "SA", "SI", "SP", "WP"]
    test_label_Basin: ["EP", "NA", "NI", "SA", "SI", "SP", "WP"]

model:
  type: "Iter_model"
  params:
    Model_choose: &Model_choose ["FPN", "CCAtt", "FengWu_AR"]
    #Many_to_Many  Many_to_One
    cmp_mode: &cmp_mode "Many_to_Many"

    is_save_vq_state: *is_use_singel_msw
    vq_name: *mswname

    is_hid_vq: *is_hid_vq
    inp_len: *input_length
    sub_model:
      FengWu_TC:
        #SELF_transformer   LSTM   ST_transformer
        backboon: "ST_transformer"
        #Origin  TFT
        decoder_backboon: "Origin"
        cmp_mode: *cmp_mode
        residual: False
        hid_residual: True
        is_load_checkpoint: True
        is_freeze_model: True
        is_freeze_future: False
        is_physics: True

        is_use_vq: True
        physics_config:
          is_cmp_PI: True
          ERA5_channels: 69
          polyorder: 2
          out_dim: 1
          dim: 128
          pre_dim: 2
          gate_rate: 0.1

        vq_tc_config:
          model_path: "VQ_VAE_TC_ERA5/world_size4-VQ_VAE_TC_ERA5/checkpoint_best.pth"
          ERA5_image_size: 40
          IR_channels: 1
          ERA5_channels: 69
          dim: &dim 128
          in_channel: 2
          num_embeddings: 1024
          embedding_dim: 128
          beta: 0.25
          n_head: 4
          is_choose_channel: False
          choose_channel_hid_dim: 128
          double_z: False
          ch_mult: [1,2,4,8]
          Cross_att_qkv_mode: "Q_TC_info"
          encoder_mode: 'FPN'
          decoder_mode: "Cross_atten"
          dropout: 0.0
        backboon_config:
          input_length: 4 
          dim: *dim
          depth: 3
          heads: 4 
          mlp_dim: 128
          dropout: 0.1
    use_ceph: True
    save_best: &loss_type "MAE"
    metrics_list: ["MAE", "MSE"]

    optimizer:
      FengWu_TC:
        type: "Adam"
        params:
          lr: 0.0001
          betas: [0.9, 0.999]
          eps: 0.000000001
    
    
    lr_scheduler:
      FengWu_TC:
        by_step: True
        sched: linear
        epochs: &maxepoch 30
        min_lr: 0.0000001
        warmup_lr: 0.0002
        warmup_epochs: 0
        lr_noise: 
        cooldown_epochs: 0

    extra_params:
      two_step_training: False
      #diff2_mae_loss   MAELoss
      loss_type: "diff2_mae_loss"
      L1_re_rate: 0.00001
      enabled_amp: False
    inp_type: *inp_type
    is_add_RI_Loss: False
    RI_threshold: 30.0
    is_diff: *is_diff
    ema_config:
      is_ema: True
      ema_decay: 0.999
      ema_add_to_train: False
    output_step_length: *output_step_length
dataset:
  train:
    <<: *gridsat_crop_fengwu_pre
    

  test:
    <<: *gridsat_crop_fengwu_pre
    



dataloader:
  num_workers: 4
  pin_memory: True
  prefetch_factor: 2
  persistent_workers: True

trainer:
  batch_size: 16
  test_batch_size: 16
  max_epoch: *maxepoch

